[18.04.2022 16:09:13] Succesfully connected to D365.
